server:
  undertow:
    io-threads: 4
    worker-threads: 128
    buffer-size: 1024
    direct-buffers: true
  servlet:
    context-path: /api
  port: 5788
spring:
  http:
    encoding:
      force: true
      enabled: true
      charset: UTF-8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: @datasource.url@
      username: @datasource.username@
      password: @datasource.password@
      initial-size: 5
      max-active: 10
      min-evictable-idle-time-millis: 100000
      validation-query: select 1
swagger:
  enabled: true
  title: "Spring Boot 测试使用 Swagger2 构建RESTful API"
  contact:
    name: "LinShaoJun"
    email: "21654428@qq.com"
    url: "https://www.yunlingfly.cn"
  version: "1.0"
  description: "API 描述"
  base-package: "com.controller"
  base-path: /**
  license: "Apache License, Version 2.0"
  license-url: "https://www.apache.org/licenses/LICENSE-2.0.html"
#  rabbitmq:
#    host: @rabbitmq.ip@
#    port: 5672
#    username: @rabbitmq.username@
#    password: @rabbitmq.password@
#    virtual-host: /
#    publisher-confirms: true    # 开启发送确认
#    publisher-returns:  true    # 开启发送失败退回
#    listener:
#      direct:
#        acknowledge-mode: manual
#      simple:
#        acknowledge-mode: manual

#MyBatis配置
mybatis:
  mapper-locations: classpath*:mapping/*/*.xml
  type-aliases-package: com.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#Mapper通用插件
mapper:
  mappers: com.MyMapper
  not-empty: false
  identity: MYSQL

#日志
logging:
  file: ./log/pay.log
  config: classpath:log4j2.xml


